-- =========================================================
-- Database Initialization Script for TTB Stock Service
-- PostgreSQL Database Design
-- =========================================================

-- 1. Create PRODUCT Table
CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_CODE VARCHAR(50) UNIQUE NOT NULL,
    PRODUCT_NAME VARCHAR(255) UNIQUE NOT NULL,
    PRODUCT_PRICE INT,
    ACTIVE BOOLEAN DEFAULT true,
    CREATE_DATE TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(255) DEFAULT 'SYSTEM',
    UPDATE_DATE TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(255) DEFAULT 'SYSTEM'
);

-- 2. Create STOCK Table with Foreign Key PRODUCT_ID
CREATE TABLE IF NOT EXISTS STOCK (
    STOCK_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID INT,
    AMOUNT INT,
    ACTIVE BOOLEAN DEFAULT true,
    CREATE_DATE TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(255) DEFAULT 'SYSTEM',
    UPDATE_DATE TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(255) DEFAULT 'SYSTEM',
    
    CONSTRAINT fk_product FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE
);

-- 3. Create TRANSACTION_LOG Table
CREATE TABLE IF NOT EXISTS TRANSACTION_LOG (
    TRANSACTION_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STOCK_ID INT,
    PRODUCT_ID INT,
    AMOUNT INT,
    CREATE_DATE TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(255) DEFAULT 'SYSTEM',

    CONSTRAINT fk_transaction_log_product FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_log_stock FOREIGN KEY(STOCK_ID) REFERENCES STOCK(STOCK_ID) ON DELETE SET NULL
);

-- 4. Indexes
CREATE INDEX IF NOT EXISTS ix_product_code ON PRODUCT(PRODUCT_CODE);
CREATE INDEX IF NOT EXISTS ix_stock_product_id ON STOCK(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS ix_transaction_log_product_id ON TRANSACTION_LOG(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS ix_transaction_log_stock_id ON TRANSACTION_LOG(STOCK_ID);
CREATE INDEX IF NOT EXISTS ix_transaction_log_create_date ON TRANSACTION_LOG(CREATE_DATE);

-- 4. Sample Seed Data
INSERT INTO PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_PRICE, ACTIVE, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY)
OVERRIDING SYSTEM VALUE
VALUES 
    ('PRD-LAPTOP-001', 'ThinkPad X1 Carbon Gen 11', 65000, TRUE, CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM'),
    ('PRD-MOUSE-001', 'Logitech MX Master 3S', 3500, TRUE, CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM'),
    ('PRD-KEYBOARD-001', 'Keychron Q1 Pro Mechanical Keyboard', 7200, TRUE, CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM')
ON CONFLICT (PRODUCT_CODE) DO NOTHING;

INSERT INTO STOCK (PRODUCT_ID, AMOUNT, ACTIVE, CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY)
OVERRIDING SYSTEM VALUE
VALUES
    (1, 50, TRUE, CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM'),
    (2, 150, TRUE, CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM'),
    (3, 80, TRUE, CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM')
ON CONFLICT DO NOTHING;
