version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ttb-stock-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "tian"
      POSTGRES_PASSWORD: "P@ssw0rd#123"
      POSTGRES_DB: "ttb_stock_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:

